use Patriziato;
SET SQL_SAFE_UPDATES = 0;
alter table Patrizio MODIFY Padre varchar(255);
alter table Patrizio MODIFY Madre varchar(255);
alter table Patrizio MODIFY Nome varchar(255);
alter table Patrizio MODIFY Cognome varchar(255);
alter table Patrizio MODIFY Vivente varchar(4);
alter table Patrizio MODIFY DirittoVoto varchar(4);
alter table Patrizio MODIFY DataNascita date;
alter table Patrizio MODIFY DataMorte date;
alter table Patrizio MODIFY DataPerdita date;
alter table Patrizio MODIFY DataInserimento date;
alter table Patrizio MODIFY Patrizio_id int auto_increment;
#insert into Patrizio values (null,1,'Amministratore','Admin',null,null,null,null,null,null,null,null,'Amministratore@email.com');
#update Patrizio set Email = 'email' where Nome = 'nome' And Cognome = 'cognome' And DataNascita = '1900/10/10';
update Patrizio set Email = 'Amministratore@email.com' where Cognome = 'Bronz' And Nome = 'Brian' And DataNascita = '1998/07/17';
update Patrizio set DataMorte = null, DataPerdita = null, DataInserimento = null where Nome = 'Miriam' And Cognome = 'Berisha-Bronz' And DataNascita = '1973/12/14';
alter table Patrizio add (foreign key(Email) references Utente(Email));